feat: NotValidVar for checking invalid valid when getting var
lekaha/playone-android pull request #69
Opened 2018-03-10 14:12 UTC by lekaha

2018-03-12 02:03 UTC, lekaha commented
@pokk 
I think they are our goal:
- We need `default constructor` for using ModelMapper
- Giving `default value` for all constructor parameters if using Data class
- But we need `specialized default` value as invalid value 

Would like to discuss about our DAO class with Delegates Properties. I think to achieve this, our choices are
- Using `normal class` with Delegates Properties to `check the value` is valid or not.
- Using `data class` with Invalid Default Value but `cannot be checked`.
- Using 'data class` with Delegates Properties but it makes more code required. (https://github.com/lekaha/playone-android/pull/69/files#diff-efec1ecfaa9115d0a7353120bcece90eR14)

What do you think?

2018-03-12 05:20 UTC, lekaha commented
@pokk If no problem please merge

2018-03-12 07:59 UTC, pokk requested changes

2018-03-12 07:59 UTC, pokk commented on ext/src/main/java/com/playone/mobile/common/NotValidVar.kt
> +            throw IllegalStateException("Property ${property.name} should be initialized before get.")
The msg is wrong. It should be `"Property ${property.name} value is invalid, please set a valid value."` or something blah blah blah.

2018-03-12 07:59 UTC, pokk commented on ext/src/main/java/com/playone/mobile/common/NotValidVar.kt
> +            throw IllegalStateException("Property ${property.name} should be initialized before get.")
Also here shouldn't throw an exception for an invliad value I think.

2018-03-12 08:44 UTC, lekaha commented
@pokk Please check again

2018-03-12 08:45 UTC, lekaha commented on ext/src/main/java/com/playone/mobile/common/NotValidVar.kt
> +            throw IllegalStateException("Property ${property.name} should be initialized before get.")
Ok, it should not be RuntimeException

2018-03-13 01:51 UTC, pokk commented on ext/src/main/java/com/playone/mobile/common/NotValidVar.kt
> +        this.value = value
`this.value = value` should be next line.

2018-03-13 03:19 UTC, pokk approved these changes

2018-03-13 07:01 UTC, merged